---
title: "In-Class Computing Task"
author: "Math 253: Statistical Computing & Machine Learning"
date: "Tuesday Sept 15, 2015"
output: 
  rmarkdown::tufte_handout
---

Today's programming tasks provide an introduction to the basic building blocks of graphics: frames, points, lines, and polygons.  In practice, you'll use higher-level graphics systems such as provided by `lattice`, `ggplot2`, `ggvis` and similar packages.  But you'll understand the use of such packages better if you know the very basics.

## Task 1: The frame

Graphics are drawn in a *frame*.  You can think of this as a piece of paper, a computer screen, or whatever space you like.  In addition to providing the physical space for drawing, the frame defines the *coordinate system* in which graphics are drawn.  We'll work with the most common system: cartesian coordinates.\marginnote{There are other coordinate systems, e.g., radial, map projections, etc.}

The basic function to draw frames is `plot()`, part of the `graphics` package that is a part of the standard R distribution.  An empty frame, with axes for the x- and y-axes is generated by this somewhat wordy command:
```{r}
plot(1, xlim = c(0, 100), ylim = c(0,100), type="n")
```
`plot()` doesn't return any value.  It's used for the *side effect* of setting up the graphics display with a frame.

## Task 2

Points at the corner of a square

## Task 3

Lines connecting the square.

Create `x2` and `y2` to create a $\gamma$-shaped path.

Create `x3` and `y3` to draw all four sides of the square.

## Task 4

Polygon and filling the square.

Polygons provide a meaning for "inside" and "outside."  You can fill the inside.  What happens when you fill the $\gamma$-shaped path.

## Task 5

Draw a circle.  Where the points come from.

## Task 6

Bells and whistles: important arguments, e.g. `col`, `lwd`, `pch`, `xlab`, `ylab`, `xaxt`, `yaxt`, ...

Transparency. `col2rgb('tomato', alpha = .1)`

Draw this complicated figure



